### ISSUE TITLE
Util.cloneDeep is not a function

### ISSUE THREAD

**Issue by lukenofurther** [cloudinary/bower-cloudinary#2] opened 2016-09-15 11:41 UTC
Whenever I try to instantiate a new instance with

`var cl = cloudinary.Cloudinary.new();`

I get this error:

`jquery.cloudinary.js:505 Uncaught TypeError: Util.cloneDeep is not a function(…)`

`Configuration  @   jquery.cloudinary.js:505`
`Cloudinary @   jquery.cloudinary.js:2177`
`Cloudinary.new @   jquery.cloudinary.js:2203`
`(anonymous function)   @   VM9760:1`

I'm including the core js library locally in my app.

**Comment by roeeba** [comment] 2017-10-03 11:39
Hi, @ljelewis. I apologise for the very late reply. I assume this is no longer relevant, but it looks like you didn't initialize Cloudinary properly. On top of `var cl = cloudinary.Cloudinary.new();` you should also declare the cloud name, like this:

```
var cl = cloudinary.Cloudinary.new(); 
        cl.config("cloud_name", "aaaaaaa");
```

If this doesn't help, please share your entire code so we can try and reproduce it on our side. 
Thanks

**Comment by roeeba** [comment] 2017-11-23 10:29
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed as completed by roeeba** 2017-11-23 10:29 UTC
Labels: question
